/* SPDX-License-Identifier: Apache-2.0 */
/* Generated by scripts/generate_rin_formats_v3.py; do not edit. */
#ifndef RIN_API_RIN_FORMATS_V3_H
#define RIN_API_RIN_FORMATS_V3_H

#include <stddef.h>
#include <stdint.h>

#define RIN_IMAGE_MAGIC UINT32_C(0x004E4952) /* RIN\0, little endian */
#define RIN_IMAGE_VERSION_3 UINT32_C(0x00030000)
#define RIN_IMAGE_ABI_MAJOR UINT16_C(0x0001)
#define RIN_IMAGE_ABI_MINOR UINT16_C(0x0002)
#define RIN_IMAGE_ABI_MINOR_SPECIAL_SECTIONS UINT16_C(0x0001)
#define RIN_IMAGE_ABI_MINOR_TLSOFF32S UINT16_C(0x0002)
#define RIN_DRIVER_IMAGE_MAGIC UINT32_C(0x5652444E) /* NDRV, little endian */
#define RIN_DRIVER_IMAGE_VERSION_3 UINT32_C(0x00030000)
#define RIN_DRIVER_ABI_MAJOR UINT16_C(0x0003)
#define RIN_DRIVER_ABI_MINOR UINT16_C(0x0000)
#define RIN_RESOURCE_MAGIC UINT32_C(0x31535252) /* RRS1, little endian */
#define RIN_RESOURCE_VERSION_1 UINT16_C(0x0001)
#define RIN_RESOURCE_MAX_COUNT UINT32_C(0x00000080)
#define RIN_RESOURCE_MAX_SECTION_SIZE UINT32_C(0x01000000)
#define RIN_ICON_RESOURCE_VERSION_1 UINT16_C(0x0001)
#define RIN_ICON_IMAGE_MAX_DIMENSION UINT16_C(0x0400)
#define RIN_ICON_IMAGE_MAX_BYTES UINT32_C(0x00400000)
#define RIN_EXPORT_VERSIONED UINT16_C(0x0001) /* RinExportV3.reserved contains the exact version string offset */

typedef enum RinImageArchitecture {
    RIN_ARCH_UNKNOWN = 0,
    RIN_ARCH_X86_64 = 1,
    RIN_ARCH_X86 = 2
} RinImageArchitecture;

typedef enum RinImageHashAlgorithm {
    RIN_IMAGE_HASH_NONE = 0,
    RIN_IMAGE_HASH_SHA256 = 1
} RinImageHashAlgorithm;

typedef enum RinImageSignatureAlgorithm {
    RIN_IMAGE_SIGNATURE_NONE = 0,
    RIN_IMAGE_SIGNATURE_RSA_PKCS1_SHA256 = 1,
    RIN_IMAGE_SIGNATURE_ED25519 = 2
} RinImageSignatureAlgorithm;

typedef enum RinImageSectionType {
    RIN_IMAGE_SECTION_INVALID = 0,
    RIN_IMAGE_SECTION_CODE = 1,
    RIN_IMAGE_SECTION_RODATA = 2,
    RIN_IMAGE_SECTION_DATA = 3,
    RIN_IMAGE_SECTION_BSS = 4,
    RIN_IMAGE_SECTION_RELOCATIONS = 5,
    RIN_IMAGE_SECTION_RESOURCES = 6,
    RIN_IMAGE_SECTION_IMPORTS = 7,
    RIN_IMAGE_SECTION_EXPORTS = 8,
    RIN_IMAGE_SECTION_TLS = 9,
    RIN_IMAGE_SECTION_UNWIND = 10,
    RIN_IMAGE_SECTION_INIT_ARRAY = 11,
    RIN_IMAGE_SECTION_FINI_ARRAY = 12
} RinImageSectionType;

typedef enum RinImageRelocationType {
    RIN_IMAGE_RELOCATION_ABS32 = 1,
    RIN_IMAGE_RELOCATION_ABS64 = 2,
    RIN_IMAGE_RELOCATION_ABS32U = 3,
    RIN_IMAGE_RELOCATION_ABS32S = 4,
    RIN_IMAGE_RELOCATION_TLSOFF32S = 5
} RinImageRelocationType;

typedef enum RinSymbolKindV3 {
    RIN_SYMBOL_FUNCTION = 1,
    RIN_SYMBOL_DATA = 2
} RinSymbolKindV3;

typedef enum RinDriverClassV3 {
    RIN_DRIVER_CLASS_CHARACTER = 0,
    RIN_DRIVER_CLASS_BLOCK = 1,
    RIN_DRIVER_CLASS_NETWORK = 2,
    RIN_DRIVER_CLASS_BUS = 3,
    RIN_DRIVER_CLASS_DISPLAY = 4,
    RIN_DRIVER_CLASS_AUDIO = 5,
    RIN_DRIVER_CLASS_INPUT = 6,
    RIN_DRIVER_CLASS_USB = 7
} RinDriverClassV3;

typedef enum RinDriverBusV3 {
    RIN_DRIVER_BUS_ANY = 0,
    RIN_DRIVER_BUS_PCI = 1,
    RIN_DRIVER_BUS_USB = 2,
    RIN_DRIVER_BUS_PLATFORM = 3,
    RIN_DRIVER_BUS_VIRTIO = 4
} RinDriverBusV3;

typedef enum RinResourceTypeV1 {
    RIN_RESOURCE_INVALID = 0,
    RIN_RESOURCE_ICON = 1,
    RIN_RESOURCE_STRING = 2,
    RIN_RESOURCE_MANIFEST = 3,
    RIN_RESOURCE_VERSION = 4,
    RIN_RESOURCE_CURSOR = 5
} RinResourceTypeV1;

typedef enum RinResourceNamespaceV1 {
    RIN_RESOURCE_NAMESPACE_APPLICATION = 1,
    RIN_RESOURCE_NAMESPACE_SYSTEM = 2
} RinResourceNamespaceV1;

typedef enum RinIconImageFormatV1 {
    RIN_ICON_FORMAT_INVALID = 0,
    RIN_ICON_FORMAT_PNG = 1,
    RIN_ICON_FORMAT_BGRA8888 = 2
} RinIconImageFormatV1;

typedef uint32_t RinImageFlags;
#define RIN_IMAGE_EXECUTABLE UINT32_C(0x00000001)
#define RIN_IMAGE_LIBRARY UINT32_C(0x00000002)
#define RIN_IMAGE_GUI UINT32_C(0x00000004)
#define RIN_IMAGE_SERVICE UINT32_C(0x00000008)
#define RIN_IMAGE_RELOCATABLE UINT32_C(0x00000010)
#define RIN_IMAGE_ASLR UINT32_C(0x00000020)
#define RIN_IMAGE_SIGNED UINT32_C(0x00000040)
#define RIN_IMAGE_USES_TLS UINT32_C(0x00000080)

typedef uint16_t RinImageSectionFlags;
#define RIN_IMAGE_SECTION_READ UINT16_C(0x0001)
#define RIN_IMAGE_SECTION_WRITE UINT16_C(0x0002)
#define RIN_IMAGE_SECTION_EXECUTE UINT16_C(0x0004)
#define RIN_IMAGE_SECTION_DISCARDABLE UINT16_C(0x0008)

typedef uint32_t RinDependencyFlags;
#define RIN_DEPENDENCY_OPTIONAL UINT32_C(0x00000001)
#define RIN_DEPENDENCY_PIN_IDENTITY UINT32_C(0x00000002)

typedef uint16_t RinImportFlagsV3;
#define RIN_IMPORT_OPTIONAL UINT16_C(0x0001)

typedef uint32_t RinDriverImageFlagsV3;
#define RIN_DRIVER_IMAGE_SIGNED UINT32_C(0x00000001)
#define RIN_DRIVER_IMAGE_RELOCATABLE UINT32_C(0x00000002)
#define RIN_DRIVER_IMAGE_USES_MSI UINT32_C(0x00000004)
#define RIN_DRIVER_IMAGE_USES_MSIX UINT32_C(0x00000008)
#define RIN_DRIVER_IMAGE_EXPERIMENTAL UINT32_C(0x00000010)

typedef uint64_t RinDriverResourceMaskV3;
#define RIN_DRIVER_RESOURCE_PCI UINT64_C(0x0000000000000001)
#define RIN_DRIVER_RESOURCE_MMIO UINT64_C(0x0000000000000002)
#define RIN_DRIVER_RESOURCE_IOPORT UINT64_C(0x0000000000000004)
#define RIN_DRIVER_RESOURCE_DMA UINT64_C(0x0000000000000008)
#define RIN_DRIVER_RESOURCE_IRQ UINT64_C(0x0000000000000010)
#define RIN_DRIVER_RESOURCE_BLOCK UINT64_C(0x0000000000000020)
#define RIN_DRIVER_RESOURCE_NETWORK UINT64_C(0x0000000000000040)
#define RIN_DRIVER_RESOURCE_INPUT UINT64_C(0x0000000000000080)
#define RIN_DRIVER_RESOURCE_DISPLAY UINT64_C(0x0000000000000100)
#define RIN_DRIVER_RESOURCE_AUDIO UINT64_C(0x0000000000000200)
#define RIN_DRIVER_RESOURCE_USB UINT64_C(0x0000000000000400)

typedef uint16_t RinDriverMatchFlagsV3;
#define RIN_DRIVER_MATCH_VENDOR_DEVICE UINT16_C(0x0001)
#define RIN_DRIVER_MATCH_SUBSYSTEM UINT16_C(0x0002)
#define RIN_DRIVER_MATCH_CLASS UINT16_C(0x0004)
#define RIN_DRIVER_MATCH_REVISION UINT16_C(0x0008)

typedef uint32_t RinResourceFlagsV1;
#define RIN_RESOURCE_FLAG_REQUIRED UINT32_C(0x00000001)

typedef uint32_t RinIconImageFlagsV1;
#define RIN_ICON_FLAG_SYMBOLIC UINT32_C(0x00000001)
#define RIN_ICON_FLAG_DARK UINT32_C(0x00000002)
#define RIN_ICON_FLAG_LIGHT UINT32_C(0x00000004)

#pragma pack(push, 1)

typedef struct RinHeaderV3 {
    uint32_t magic;
    uint32_t version;
    uint16_t header_size;
    uint16_t architecture;
    uint16_t abi_major;
    uint16_t abi_minor;
    uint32_t flags;
    uint32_t section_count;
    uint32_t dependency_count;
    uint64_t entry_rva;
    uint64_t preferred_base;
    uint64_t image_size;
    uint64_t required_cpu_features;
    uint64_t required_capabilities;
    uint64_t section_table_offset;
    uint64_t dependency_table_offset;
    uint64_t string_table_offset;
    uint64_t string_table_size;
    uint64_t signature_offset;
    uint32_t signature_size;
    uint16_t signature_algorithm;
    uint16_t hash_algorithm;
    uint8_t content_hash[32];
    uint32_t reserved0;
    uint64_t reserved[13];
} RinHeaderV3;

typedef struct RinSectionV3 {
    uint16_t type;
    uint16_t flags;
    uint32_t alignment;
    uint64_t file_offset;
    uint64_t file_size;
    uint64_t virtual_address;
    uint64_t memory_size;
    uint32_t name_offset;
    uint32_t reserved;
} RinSectionV3;

typedef struct RinDependencyV3 {
    uint32_t name_offset;
    uint16_t minimum_abi_major;
    uint16_t minimum_abi_minor;
    uint32_t flags;
    uint8_t identity_hash[16];
    uint32_t reserved;
} RinDependencyV3;

typedef struct RinRelocationV3 {
    uint64_t virtual_address;
    uint16_t type;
    uint16_t reserved0;
    uint32_t reserved1;
} RinRelocationV3;

typedef struct RinImportV3 {
    uint32_t name_offset;
    uint32_t dependency_index;
    uint64_t target_rva;
    uint16_t kind;
    uint16_t flags;
    uint32_t reserved0;
    uint64_t reserved1;
} RinImportV3;

typedef struct RinExportV3 {
    uint32_t name_offset;
    uint16_t kind;
    uint16_t flags;
    uint64_t virtual_address;
    uint64_t size;
    uint64_t reserved;
} RinExportV3;

typedef struct RinResourceHeaderV1 {
    uint32_t magic;
    uint16_t version;
    uint16_t header_size;
    uint32_t resource_count;
    uint32_t resource_entry_size;
    uint32_t resource_table_offset;
    uint32_t string_table_offset;
    uint32_t string_table_size;
    uint32_t namespace_id;
    uint32_t flags;
    uint32_t section_size;
    uint32_t reserved;
} RinResourceHeaderV1;

typedef struct RinResourceEntryV1 {
    uint16_t type;
    uint16_t flags;
    uint32_t resource_id;
    uint32_t name_offset;
    uint32_t data_offset;
    uint32_t data_size;
    uint32_t reserved[3];
} RinResourceEntryV1;

typedef struct RinIconResourceV1 {
    uint16_t version;
    uint16_t header_size;
    uint32_t image_count;
    uint32_t image_entry_size;
    uint32_t image_table_offset;
    uint32_t flags;
    uint32_t reserved[3];
} RinIconResourceV1;

typedef struct RinIconImageV1 {
    uint16_t width;
    uint16_t height;
    uint16_t scale_numerator;
    uint16_t scale_denominator;
    uint32_t format;
    uint32_t flags;
    uint32_t data_offset;
    uint32_t data_size;
    uint32_t variant;
    uint32_t reserved[3];
} RinIconImageV1;

typedef struct RinDriverHeaderV3 {
    uint32_t magic;
    uint32_t version;
    uint16_t header_size;
    uint16_t architecture;
    uint16_t abi_major;
    uint16_t abi_minor;
    uint16_t driver_class;
    uint16_t reserved0;
    uint32_t flags;
    uint32_t section_count;
    uint32_t match_count;
    uint64_t image_size;
    uint64_t required_cpu_features;
    uint64_t required_resources;
    uint64_t section_table_offset;
    uint64_t match_table_offset;
    uint64_t string_table_offset;
    uint64_t string_table_size;
    uint64_t probe_rva;
    uint64_t start_rva;
    uint64_t stop_rva;
    uint64_t remove_rva;
    uint64_t power_rva;
    uint64_t signature_offset;
    uint32_t signature_size;
    uint16_t signature_algorithm;
    uint16_t hash_algorithm;
    uint8_t content_hash[32];
    uint64_t reserved[10];
} RinDriverHeaderV3;

typedef struct RinDriverMatchV3 {
    uint16_t bus_type;
    uint16_t flags;
    uint16_t vendor_id;
    uint16_t device_id;
    uint16_t subsystem_vendor_id;
    uint16_t subsystem_device_id;
    uint32_t class_code;
    uint32_t class_mask;
    uint32_t revision;
    uint32_t revision_mask;
    uint32_t name_offset;
    uint32_t reserved0;
    uint64_t required_resources;
    uint32_t reserved1;
    uint64_t reserved[2];
} RinDriverMatchV3;

#pragma pack(pop)

#if defined(__cplusplus)
static_assert(sizeof(RinHeaderV3) == 256u, "RinHeaderV3 ABI drift");
static_assert(sizeof(RinSectionV3) == 48u, "RinSectionV3 ABI drift");
static_assert(sizeof(RinDependencyV3) == 32u, "RinDependencyV3 ABI drift");
static_assert(sizeof(RinRelocationV3) == 16u, "RinRelocationV3 ABI drift");
static_assert(sizeof(RinImportV3) == 32u, "RinImportV3 ABI drift");
static_assert(sizeof(RinExportV3) == 32u, "RinExportV3 ABI drift");
static_assert(sizeof(RinResourceHeaderV1) == 44u, "RinResourceHeaderV1 ABI drift");
static_assert(sizeof(RinResourceEntryV1) == 32u, "RinResourceEntryV1 ABI drift");
static_assert(sizeof(RinIconResourceV1) == 32u, "RinIconResourceV1 ABI drift");
static_assert(sizeof(RinIconImageV1) == 40u, "RinIconImageV1 ABI drift");
static_assert(sizeof(RinDriverHeaderV3) == 256u, "RinDriverHeaderV3 ABI drift");
static_assert(sizeof(RinDriverMatchV3) == 64u, "RinDriverMatchV3 ABI drift");
static_assert(offsetof(RinHeaderV3, content_hash) == 116u, "RinHeaderV3.content_hash ABI drift");
static_assert(offsetof(RinDriverHeaderV3, content_hash) == 144u, "RinDriverHeaderV3.content_hash ABI drift");
static_assert(offsetof(RinDriverMatchV3, required_resources) == 36u, "RinDriverMatchV3.required_resources ABI drift");
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
_Static_assert(sizeof(RinHeaderV3) == 256u, "RinHeaderV3 ABI drift");
_Static_assert(sizeof(RinSectionV3) == 48u, "RinSectionV3 ABI drift");
_Static_assert(sizeof(RinDependencyV3) == 32u, "RinDependencyV3 ABI drift");
_Static_assert(sizeof(RinRelocationV3) == 16u, "RinRelocationV3 ABI drift");
_Static_assert(sizeof(RinImportV3) == 32u, "RinImportV3 ABI drift");
_Static_assert(sizeof(RinExportV3) == 32u, "RinExportV3 ABI drift");
_Static_assert(sizeof(RinResourceHeaderV1) == 44u, "RinResourceHeaderV1 ABI drift");
_Static_assert(sizeof(RinResourceEntryV1) == 32u, "RinResourceEntryV1 ABI drift");
_Static_assert(sizeof(RinIconResourceV1) == 32u, "RinIconResourceV1 ABI drift");
_Static_assert(sizeof(RinIconImageV1) == 40u, "RinIconImageV1 ABI drift");
_Static_assert(sizeof(RinDriverHeaderV3) == 256u, "RinDriverHeaderV3 ABI drift");
_Static_assert(sizeof(RinDriverMatchV3) == 64u, "RinDriverMatchV3 ABI drift");
_Static_assert(offsetof(RinHeaderV3, content_hash) == 116u, "RinHeaderV3.content_hash ABI drift");
_Static_assert(offsetof(RinDriverHeaderV3, content_hash) == 144u, "RinDriverHeaderV3.content_hash ABI drift");
_Static_assert(offsetof(RinDriverMatchV3, required_resources) == 36u, "RinDriverMatchV3.required_resources ABI drift");
#endif

#endif /* RIN_API_RIN_FORMATS_V3_H */
